### ISSUE TITLE
Sticky header width on PR files

### ISSUE THREAD

**Issue by Katsute** [KatsuteDev/GitHub-Center#43]
Sticky header needs full background width on PR file preview

![Image](https://github.com/user-attachments/assets/01b69615-fe2f-4edf-92cf-619a36c7d3bd)

**Comment by Katsute** [comment]
not fixable, attempted with css but janky github css is not rehiding the toolbar when scrolling back to the top

```css
.pr-toolbar.position-stuck {
    margin-left: 100vw !important;
    margin-right: 100vw !important;
    max-width: 100vw !important;
}
```
